// layout.js
import Script from 'next/script';
import Navbar from '@/components/Navbar';
import './assets/css/plugins.css';
import './assets/css/style.css';
import './assets/css/colors/grape.css';
import './assets/css/fonts/space.css';
import Footer from '@/components/Footer';

export const metadata = {
  title: "Fath School",
  description: "Generated by create next app",
  // Tambahkan metadata lain yang diperlukan di sini
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className='content-wrapper'>
          <Navbar />
          {children}
          <Footer />
        </div>
        <Script src="/assets/js/plugins.js" strategy="afterInteractive" />
        <Script src="/assets/js/theme.js" strategy="afterInteractive" />
      </body>
    </html>
  );
}