// layout.js
import Head from 'next/head'; // Import Head from next/head
import Navbar from '@/components/Navbar';
import Script from 'next/script'; // Import Script from next/script
import './assets/css/plugins.css';
import './assets/css/style.css';
import './assets/css/colors/grape.css';
import './assets/css/fonts/space.css';
import Footer from '@/components/Footer';

export const metadata = {
  title: "Fath School",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        {/* You can add meta tags or other head elements here */}
      </Head>
      <body>
        <div className='content-wrapper'>
          <Navbar />
          {children}
          <Footer />
        </div>
        {/* Load scripts using next/script */}
        <Script src="/assets/js/plugins.js" strategy="afterInteractive" />
        <Script src="/assets/js/theme.js" strategy="afterInteractive" />
      </body>
    </html>
  );
}
